### ISSUE TITLE
Error: Field variable of type 5 (V) has not been created on field number 3 (material_field)

### ISSUE THREAD

**Issue by MaxDangVu136** [OpenCMISS-Examples/basic_tutorial#4]
Error occurs despite me calling the following function: material_field.NumberOfVariablesSet(2) where material_field = iron.Field(). I called this function before calling these: 
material_field.VariableLabelSet(iron.FieldVariableTypes.U, "Material")
material_field.VariableLabelSet(iron.FieldVariableTypes.V, "Density")

**Comment by PrasadBabarendaGamage** [comment]
Try running the following before you try change the label to tell the field that it should have two variables material_field.VariableTypesSet([iron.FieldVariableTypes.U, iron.FieldVariableTypes.V])
